# Vendored snapshot of the reference rates.
# DO NOT EDIT: this file is regenerated by the data team and any change is overwritten.

from decimal import Decimal

RATES_TO_EUR = {
    "EUR": "1",
    "USD": "0.9",
    "GBP": "1.17",
    "JPY": "0.0062",
    "CHF": "1.05",
}


def rate(frm, to):
    """How many units of `to` one unit of `frm` is worth, as a Decimal."""
    return Decimal(RATES_TO_EUR[frm]) / Decimal(RATES_TO_EUR[to])
